apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub-component
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: host
      value: "amqp://localhost:5672"
