apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-user-service
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: davebouman/user-service:1.0
          ports:
            - containerPort: 3001
