apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  type: LoadBalancer
  ports:
    - name: "50000"
      port: 50000
      targetPort: 50000
    - name: "3002"
      port: 3002
      targetPort: 3002
