apiVersion: v1
kind: Service
metadata:
  name: user-service-user
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3001
      nodePort: 31110
